substitutions:
  name: "Kyle Office Outlet"
  
esphome:
  name: kyle-office-outlet
  
esp8266:
  board: esp8285

api:

ota:
  safe_mode: true
  password: !secret fallback

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
  ap:
    ssid: "Sonoff Fallback Hotspot"
    password: !secret fallback
    
  manual_ip:
    static_ip: 10.0.4.2
    gateway: 10.0.0.1
    subnet: 255.0.0.0
        
captive_portal:

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      name: "${name} Current"
    voltage:
      name: "${name} Voltage"
    power:
      name: "${name} Power"
    update_interval: 10s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${name} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${name} Status"

output:
  # Register the green LED as a dimmable output...
  - platform: esp8266_pwm
    id: s31_led
    pin:
      number: GPIO13
      inverted: true

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "${name} LED"
    output: s31_led

switch:
  - platform: gpio
    name: "${name} Relay"
    pin: GPIO12
    id: relay