esphome:
  name: "rowan-temp"

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 10.0.3.1
    gateway: 10.0.0.1
    subnet: 255.0.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome Hotspot"
    password: !secret fallback

captive_portal:

logger:
  logs:
    sensor: none

api:
ota:

sensor:
  - platform: dht
    model: DHT22
    pin: D1
    temperature:
      name: "Rowan Temperature"
      id: temperature
    humidity:
      name: "Rowan Humidity"
      id: humidity
    update_interval: 60s